### ISSUE TITLE
error about no found libc

### ISSUE THREAD

**Issue by chuixifeng** [cc-morning/share-clip#6]
redis 5.0.3
ubuntu 20 

![图片](https://user-images.githubusercontent.com/22932752/150668504-3ccdbe25-9ed4-4440-8404-44f09bff88f8.png)

**Comment by cc-morning** [comment]
Sorry for the late reply, it's because the version of glibc on the machine where it was packaged is too high and the version on your machine is too low. I will resend a new version later and you can try it.

**Comment by cc-morning** [comment]
You can try this [share-clip.gz](https://github.com/cc-morning/share-clip/files/7942648/share-clip.gz)

**Comment by chuixifeng** [comment]
thank your 
it running fine
