### ISSUE TITLE
请问你最终解决了arboard内存泄露问题吗

### ISSUE THREAD

**Issue by ChurchTao** [cc-morning/share-clip#9]
我也遇到了他内存泄露的问题

**Comment by ChurchTao** [comment]
大佬，想和你交流一下~

**Comment by ChurchTao** [comment]
@morn-0 
大佬，想和你交流一下~

**Comment by ChurchTao** [comment]
哦 没我最后解决了，没事儿了是 objc 的问题
[https://github.com/1Password/arboard/pull/97](https://github.com/1Password/arboard/pull/97)

**Comment by hxcliff** [comment]
> 哦 没我最后解决了，没事儿了是 objc 的问题 [1Password/arboard#97](https://github.com/1Password/arboard/pull/97)

恩，这应该只是[mac平台](https://github.com/1Password/arboard/pull/28)暂时没问题了，但是我之前发现windows和linux似乎还是有问题。具体原因没有去深究了

**Comment by ChurchTao** [comment]
原来如此，这玩意儿坑这么多吗，我看用的人还挺多的
